chore: go back to semantic-release 24.2.3 to fix release failures
Starting from this [commit](https://github.com/lydavid/MusicSearch/commit/f613177b13e329389abec02ed59fae5f3da317f8) that updated semantic-release, non-chores-only releases started failing.

This chores-only release was successful: https://github.com/lydavid/MusicSearch/actions/runs/15156461773/job/42612898070

The first failed release: https://github.com/lydavid/MusicSearch/actions/runs/15180969139/job/42690706055
> [7:56:18 AM] [semantic-release] › ✘  An error occurred while running semantic-release: TypeError: text.replace is not a function
> Please report this to https://github.com/markedjs/marked.

I reran it, and it succeeded because the second run did not require creating change logs. Despite the first run failing, it still created a [GitHub release](https://github.com/lydavid/MusicSearch/releases/tag/v1.31.0).

The next failed release: https://github.com/lydavid/MusicSearch/actions/runs/15205090585/job/42767062010 had the same error and produced this [GitHub release](https://github.com/lydavid/MusicSearch/releases/tag/v1.31.1) that was missing the android apks. It created this [commit](https://github.com/lydavid/MusicSearch/commit/502f2bc870c474ca6a2e4951f1c4eaa03b29dd1c) which came about from skipping the bump version name/code steps that would have come after getting the release version.

The relevant upstream issue: https://github.com/markedjs/marked/issues/3689.