fix: crash when intent is null
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
    net.openid.appauth.Preconditions.checkNotNull(Preconditions.java:39)
    net.openid.appauth.AuthorizationException.fromIntent(AuthorizationException.java:572)
    ly.david.musicsearch.data.musicbrainz.auth.MusicBrainzLoginActivityResultContract.parseResult(MusicBrainzLoginActivityResultContract.kt:60)