fix: delete artist credits linked to tracks when refreshing tracks which will prevent duplicate tracks from appearing after changes are made on MusicBrainz's server (#1256)
Duplicate tracks appear because we join with `artist_credit_entity` but never delete it from refreshing, so both the old and new artist credits will appear:

<img width="1624" alt="Screenshot 2024-11-30 at 8 42 05 PM" src="https://github.com/user-attachments/assets/f989e387-7a25-4524-9377-fbd4fdd87792">

Setting `keyed = false` in `TracksByReleaseUi` will stop the crash and reveal this:
![Screenshot_20241130_200631](https://github.com/user-attachments/assets/a01a0c02-1e3c-4558-ac1b-f22e86f726c4)

The crash happens because of this:

```
java.lang.IllegalArgumentException: Key "d66d44df-43de-40e4-a43b-cb780cb42cd7" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
```

#1248