Revert "chore(ci): try configuration cache (#260)"
This reverts commit ed63424b9536fbcc1e41a6dad73839ab96b899c5.

error: https://scans.gradle.com/s/y7svkam3mt5em