fix: do not crash if we somehow insert two release groups for a given release
I'm uncertain how this is possible but it may happen after releases and release groups are merged in MusicBrainz and we still have outdated data as we navigate through our app, mixing new and old data.

```
java.lang.IllegalStateException: ResultSet returned more than 1 row for release_group.sq:getReleaseGroupForRelease
    app.cash.sqldelight.ExecutableQuery$executeAsOneOrNull$1.invoke(Query.kt:201)
```